version: '2'

services:
  nodeapi:
    image: node/api-jobs
    build:
      context: ../recipes/node/
      args:
        USER: ${ENV_USER}
        GID: ${ENV_GID}
        UID: ${ENV_UID}
  mysql:
    image: lucydb
    build:
      context: ../recipes/lucydb/
